const { exec } = require("child_process");
const { promisify } = require("util");

/**
 * Briefing Engine (Story 5.1: Multi-Source Briefing Synthesis)
 *
 * Collects local context (pending jobs, processing documents, recent vault notes)
 * and passes to local LLM (Ollama) to generate a structured daily briefing.
 *
 * v0.1: Local data only (job queue, vault context). No external APIs.
 * OAuth integration deferred to v0.2 (ADR22).
 *
 * AC1: Daily briefing note generated each morning in designated folder
 * AC2: Output includes distinct sections: agenda, action items, contextual reminders
 */

const execAsync = promisify(exec);

async function collectBriefingContext(db, cfg) {
  const context = {
    timestamp: new Date().toISOString(),
    sections: {
      agenda: [],
      actionItems: [],
      contextReminders: [],
    },
  };

  try {
    // Section 1: Agenda — Pending jobs (ingest, classify, index)
    const jobRows = db.prepare(`
      SELECT id, job_type, status, created_at FROM job
      WHERE status IN ('New', 'Running')
      ORDER BY created_at DESC LIMIT 10
    `).all();

    context.sections.agenda = jobRows.map(j => ({
      type: j.job_type,
      id: j.id,
      status: j.status,
      created: j.created_at,
    }));

    // Section 2: Action Items — Documents in "Processing" state
    const docRows = db.prepare(`
      SELECT id, uri_location, status FROM document
      WHERE status = 'Processing'
      ORDER BY created_at DESC LIMIT 10
    `).all();

    context.sections.actionItems = docRows.map(d => ({
      uri: d.uri_location,
      id: d.id,
      status: d.status,
    }));

    // Section 3: Context Reminders — Recent vault notes (in-memory; full search via 6.2)
    // For v0.1, just reference recent documents with completed jobs
    const completedDocs = db.prepare(`
      SELECT id, uri_location FROM document
      WHERE status = 'Indexed'
      ORDER BY updated_at DESC LIMIT 5
    `).all();

    context.sections.contextReminders = completedDocs.map(d => ({
      uri: d.uri_location,
      id: d.id,
    }));
  } catch (err) {
    console.error("Error collecting briefing context:", err);
  }

  return context;
}

async function generateBriefing(ollamaClient, context) {
  /**
   * Generate briefing via local LLM.
   * Prompt structured to produce Markdown with clear sections.
   */
  const prompt = `
Generate a daily briefing for a knowledge worker. Use the following context:

AGENDA (Pending processing jobs):
${context.sections.agenda.map(a => `- ${a.type} job #${a.id} (${a.status})`).join("\n")}

ACTION ITEMS (Documents awaiting tagging/indexing):
${context.sections.actionItems.map(a => `- ${a.uri} (${a.status})`).join("\n")}

CONTEXTUAL REMINDERS (Recently completed work):
${context.sections.contextReminders.map(r => `- ${r.uri}`).join("\n")}

Create a brief, structured briefing with three sections:
1. **Agenda** — Summary of today's processing priorities
2. **Action Items** — What needs attention
3. **Contextual Reminders** — Relevant recent work

Keep it concise (< 500 words). Use Markdown formatting.
`;

  try {
    const response = await ollamaClient.chat({
      model: "llama3.2:3b",
      messages: [{ role: "user", content: prompt }],
      stream: false,
    });

    return response.message.content;
  } catch (err) {
    throw new Error(`Ollama briefing generation failed: ${err.message}`);
  }
}

async function writeBriefingNote(vaultDir, briefingContent) {
  /**
   * Write briefing to $VAULT_DIR/daily-notes/briefing-YYYYMMDD.md
   */
  const path = require("path");
  const fs = require("fs").promises;

  const today = new Date().toISOString().split("T")[0]; // YYYY-MM-DD
  const notesDir = path.join(vaultDir, "daily-notes");
  const briefingPath = path.join(notesDir, `briefing-${today}.md`);

  // Create directory if it doesn't exist
  await fs.mkdir(notesDir, { recursive: true });

  // Write briefing note with YAML frontmatter
  const note = `---
title: Daily Briefing — ${today}
created: ${new Date().toISOString()}
tags: [briefing, daily]
---

# Daily Briefing — ${today}

${briefingContent}

---
*Generated by 4thBrain Briefing Engine*
`;

  await fs.writeFile(briefingPath, note, "utf-8");
  return briefingPath;
}

async function generateDailyBriefing(db, cfg, ollamaClient) {
  /**
   * Main entry point for briefing generation.
   * Called by Story 4.1's batch worker.
   *
   * AC1: Note generated each morning ✓
   * AC2: Three distinct sections ✓
   */
  try {
    const context = await collectBriefingContext(db, cfg);
    const briefingContent = await generateBriefing(ollamaClient, context);
    const notePath = await writeBriefingNote(cfg.VAULT_DIR, briefingContent);

    return {
      status: "success",
      briefing_path: notePath,
      sections_generated: Object.keys(context.sections),
      timestamp: context.timestamp,
    };
  } catch (err) {
    return {
      status: "failed",
      error: err.message,
    };
  }
}

module.exports = {
  collectBriefingContext,
  generateBriefing,
  writeBriefingNote,
  generateDailyBriefing,
};
